version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
    groups:
      bundler-dev:
        dependency-type: "development"
        patterns:
          - "*"
      bundler-production:
        dependency-type: "production"
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
