name: Global Database Integration Tests

on:
  workflow_dispatch:
  schedule:
    # Every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'

permissions:
  id-token: write
  contents: read

jobs:
  gdb-integration-tests:
    name: GDB Integration Tests (${{ matrix.environment }})
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        environment: [ 'gdb-mysql', 'gdb-pg' ]

    steps:
      - name: 'Clone repository'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: 'Validate Gradle wrapper'
        uses: gradle/actions/wrapper-validation@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0

      - name: 'Set up Ruby 4.0'
        uses: ruby/setup-ruby@a0102e0972be65f351c307e2d64b9314a57c8073 # v1
        with:
          ruby-version: '4.0'
          bundler-cache: true

      - name: 'Set up JDK 8'
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6
        with:
          distribution: 'corretto'
          java-version: 8

      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: ruby_gdb_integration_tests
          role-duration-seconds: 21600
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: 'Run GDB Integration Tests'
        run: ./gradlew --no-parallel --no-daemon :integration-testing:test-${{ matrix.environment }} --info
        env:
          RDS_DB_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          GDB_SECONDARY_REGION: ${{ secrets.GDB_SECONDARY_REGION }}

      - name: 'Archive GDB results'
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: rspec-gdb-integration-report-${{ matrix.environment }}
          path: ./spec/integration/host/build/reports/tests/test/
          if-no-files-found: ignore
          retention-days: 14
