name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  lts-integration-tests:
    name: Run LTS Integration Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [ 'mysql', 'pg' ]

    steps:
      - name: 'Clone repository'
        uses: actions/checkout@v7

      - name: 'Set up Ruby 3.3'
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: 'Set up JDK 8'
        uses: actions/setup-java@v6
        with:
          distribution: 'corretto'
          java-version: 8

      - name: 'Set up Gradle'
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0

      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: ruby_integration_tests
          role-duration-seconds: 21600
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: 'Run LTS Integration Tests'
        run: ./gradlew --no-parallel --no-daemon :integration-testing:test-ruby-3.3-${{ matrix.environment }} --info
        env:
          RDS_DB_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          MYSQL_VERSION: default
          PG_VERSION: default

      - name: 'Archive LTS results'
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: rspec-integration-report-3.3-${{ matrix.environment }}-lts
          path: ./spec/integration/host/build/reports/tests/test/
          if-no-files-found: ignore
          retention-days: 5

  latest-integration-tests:
    name: Run Latest Integration Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [ 'mysql', 'pg' ]

    steps:
      - name: 'Clone repository'
        uses: actions/checkout@v7

      - name: 'Set up Ruby 4.0'
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1
        with:
          ruby-version: '4.0'
          bundler-cache: true

      - name: 'Set up JDK 8'
        uses: actions/setup-java@v6
        with:
          distribution: 'corretto'
          java-version: 8

      - name: 'Set up Gradle'
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0

      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: ruby_integration_tests
          role-duration-seconds: 21600
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: 'Run Latest Integration Tests'
        run: ./gradlew --no-parallel --no-daemon :integration-testing:test-ruby-4.0-${{ matrix.environment }} --info
        env:
          RDS_DB_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          MYSQL_VERSION: latest
          PG_VERSION: latest

      - name: 'Archive Latest results'
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: rspec-integration-report-4.0-${{ matrix.environment }}-latest
          path: ./spec/integration/host/build/reports/tests/test/
          if-no-files-found: ignore
          retention-days: 5

  multi-az-integration-tests:
    name: Run Multi-AZ Cluster Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        environment: [ 'mysql', 'pg' ]

    steps:
      - name: 'Clone repository'
        uses: actions/checkout@v7

      - name: 'Set up Ruby 3.3'
        uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: 'Set up JDK 8'
        uses: actions/setup-java@v6
        with:
          distribution: 'corretto'
          java-version: 8

      - name: 'Set up Gradle'
        uses: gradle/actions/setup-gradle@748248ddd2a24f49513d8f472f81c3a07d4d50e1 # v4.4.4

      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: ruby_multi_az_integration_tests
          role-duration-seconds: 21600
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: 'Run Multi-AZ Integration Tests'
        run: ./gradlew --no-parallel --no-daemon :integration-testing:test-${{ matrix.environment }}-multi-az --info
        env:
          RDS_DB_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: 'Archive Multi-AZ results'
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: rspec-integration-report-multi-az-${{ matrix.environment }}
          path: ./spec/integration/host/build/reports/tests/test/
          if-no-files-found: ignore
          retention-days: 5
