name: Run Blue/Green Integration Tests

on:
  workflow_dispatch:
  schedule:
    # Every Sunday at 9:00 AM UTC
    - cron: '0 9 * * 0'

permissions:
  id-token: write
  contents: read

jobs:
  bg-integration-tests:
    name: BG Integration Tests (${{ matrix.testTask }})
    runs-on: codebuild-rubyWrapper-${{ github.run_id }}-${{ github.run_attempt }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        testTask:
          - test-bgd-mysql-aurora
          - test-bgd-pg-aurora
          - test-bgd-mysql-instance
          - test-bgd-pg-instance
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: 'Validate Gradle wrapper'
        uses: gradle/actions/wrapper-validation@3f5f9adaf7d9fecd50b5935e54106014257a94e6 # v6.4.0

      - uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8 # v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6
        with:
          distribution: 'corretto'
          java-version: '8'

      - uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: ruby_bg_integration_tests
          role-duration-seconds: 21600
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run BG Integration Tests
        run: ./gradlew --no-parallel --no-daemon :integration-testing:${{ matrix.testTask }} --info
        env:
          RDS_DB_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Archive results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: bg-report-${{ matrix.testTask }}
          path: ./spec/integration/host/build/reports/tests/test/
          retention-days: 5
